version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .devcontainer/.env
    volumes:
      - ./:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
